/**
 * Created by ma on 2017/7/25.
 */
export const COMMUNITY_FIRST_LOADING = 'COMMUNITY_FIRST_LOADING'
export const COMMUNITY_HOME_LOADING = 'COMMUNITY_HOME_LOADING'
export const COMMUNITY_ALERT = 'COMMUNITY_ALERT'
export const COMMUNITY_ALERT_TITLE = 'COMMUNITY_ALERT_TITLE'

//社区首页
export const COMMUNITY_TITLE = 'COMMUNITY_TITLE'
export const COMMUNITY_HOME_LIST = 'COMMUNITY_HOME_LIST'
export const COMMUNITY_BANNER_DATA = 'COMMUNITY_BANNER_DATA'
export const COMMUNITY_CATE_DATA = 'COMMUNITY_CATE_DATA'
export const COMMUNITY_CATE_ARTIST = 'COMMUNITY_CATE_ARTIST'
export const COMMUNITY_HOME_PAGE = 'COMMUNITY_HOME_PAGE'

//社区详情
export const COMMUNITY_DETAILID = 'COMMUNITY_DETAILID'
export const COMMUNITY_DETAILDATA = 'COMMUNITY_DETAILDATA'
export const COMMUNITY_DETAIL_COMMENT = 'COMMUNITY_DETAIL_COMMENT'

export const CHANGE_PRAISE_STATUS = 'CHANGE_PRAISE_STATUS'


//社区评论详情
export const COMMUNITY_COMMENTDATA = 'COMMUNITY_COMMENTDATA'
export const COMMUNITY_COMMENTLIST = 'COMMUNITY_COMMENTLIST'
export const COMMUNITY_COMMENT_PAGE = 'COMMUNITY_COMMENT_PAGE'
export const COMMUNITY_COMMENT_REPLYCOUNT = 'COMMUNITY_COMMENT_REPLYCOUNT'

export const CHANGE_SHOWEDIT_STATUS = 'CHANGE_SHOWEDIT_STATUS'


//圈子信息
export const COMMUNITY_PER_CIRCLEID = 'COMMUNITY_PER_CIRCLEID'
export const COMMUNITY_PER_CATESTANDARD = 'COMMUNITY_PER_CATESTANDARD'
export const COMMUNITY_PER_ALPHA = 'COMMUNITY_PER_ALPHA'
export const COMMUNITY_PER_SELECTCODE = 'COMMUNITY_PER_SELECTCODE'
export const COMMUNITY_PER_DATALIST = 'COMMUNITY_PER_DATALIST'
export const COMMUNITY_PER_CATEDATA = 'COMMUNITY_PER_CATEDATA'
export const COMMUNITY_PER_CHILDCIRCLELIST = 'COMMUNITY_PER_CHILDCIRCLELIST'
export const COMMUNITY_PER_PAGE = 'COMMUNITY_PER_PAGE'

export const CHANGE_ATTENTION_STATUS = 'CHANGE_ATTENTION_STATUS'

//更多圈子
export const COMMUNITY_MORE_DATALIST = 'COMMUNITY_MORE_DATALIST'
export const COMMUNITY_MORE_PAGE = 'COMMUNITY_MORE_PAGE'

export const CHANGE_MORE_PAGE = 'CHANGE_MORE_PAGE'


