/**
 * Created by jemmy_wxh on 2017/12/5.
 */
export const REWARD_FIRST_LOADING = 'REWARD_FIRST_LOADING'
export const REWARD_HOME_LOADING = 'REWARD_HOME_LOADING'
export const REWARD_ALERT = 'REWARD_ALERT'
export const REWARD_ALERT_TITLE = 'REWARD_ALERT_TITLE'

//抽抽抽
export const REWARD_TITLE = 'REWARD_TITLE'

export const REWARD_LIST_DATA = 'REWARD_LIST_DATA'
export const REWARD_INDEX_PAGE = 'REWARD_INDEX_PAGE'
export const REWARD_INDEX_LUCKY_DATA = 'REWARD_INDEX_LUCKY_DATA'

export const REWARD_DETAIL_DATA = 'REWARD_DETAIL_DATA'
export const REWARD_DETAIL_LUCKY_DATA = 'REWARD_DETAIL_LUCKY_DATA'